// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// LocAvg
List LocAvg(List NonZeroCell, List NonZeroGene, NumericVector r, NumericVector h, const double a);
RcppExport SEXP _bIbW_LocAvg(SEXP NonZeroCellSEXP, SEXP NonZeroGeneSEXP, SEXP rSEXP, SEXP hSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type NonZeroCell(NonZeroCellSEXP);
    Rcpp::traits::input_parameter< List >::type NonZeroGene(NonZeroGeneSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type h(hSEXP);
    Rcpp::traits::input_parameter< const double >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(LocAvg(NonZeroCell, NonZeroGene, r, h, a));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bIbW_LocAvg", (DL_FUNC) &_bIbW_LocAvg, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_bIbW(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
